blueprint:
  name: Paralelo Virtual (Ultra Rápido)
  description: Sincroniza switches/lights instantaneamente com proteção anti-loop e performance otimizada
  domain: automation
  input:
    entrada_switchs:
      name: Pontos de Iluminação
      description: Selecione os dispositivos para sincronizar
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input entrada_switchs
    to:
      - 'on'
      - 'off'

condition:
  # Condição simplificada - apenas evita loop direto
  - condition: template
    value_template: >
      {{ trigger.to_state.context.id != this.context.id
         and trigger.to_state.state != trigger.from_state.state }}

variables:
  entidades: !input entrada_switchs
  # Lista otimizada de entidades para sincronizar
  outros: >
    {{ entidades | reject('equalto', trigger.entity_id) | list }}
  # Estado alvo capturado
  novo_estado: "{{ trigger.to_state.state }}"

action:
  # Execução paralela para máxima velocidade
  - parallel:
      - service: "homeassistant.turn_{{ novo_estado }}"
        target:
          entity_id: "{{ outros }}"
        continue_on_error: true
      
      # Força atualização de estado se necessário
      - service: homeassistant.update_entity
        target:
          entity_id: "{{ outros }}"
        continue_on_error: true
